CREATE TABLE IF NOT EXISTS `media_item` (
    `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    `public_id` CHAR(22) NOT NULL,
    `user_id` BIGINT UNSIGNED NOT NULL,
    `platform` VARCHAR(20) NOT NULL,
    `external_id` VARCHAR(128) DEFAULT NULL,
    `source_url` VARCHAR(1024) DEFAULT NULL,
    `title` VARCHAR(255) NOT NULL,
    `creator` VARCHAR(255) DEFAULT NULL,
    `cover_url` VARCHAR(1024) DEFAULT NULL,
    `duration_ms` BIGINT UNSIGNED DEFAULT NULL,
    `playback_type` VARCHAR(30) NOT NULL,
    `storage_key` VARCHAR(512) DEFAULT NULL,
    `mime_type` VARCHAR(128) DEFAULT NULL,
    `file_size` BIGINT UNSIGNED DEFAULT NULL,
    `language` VARCHAR(20) DEFAULT NULL,
    `cefr_level` VARCHAR(10) DEFAULT NULL,
    `wpm` INT DEFAULT NULL,
    `status` VARCHAR(30) NOT NULL DEFAULT 'CREATED',
    `processing_stage` VARCHAR(40) NOT NULL DEFAULT 'VALIDATING',
    `error_message` TEXT DEFAULT NULL,
    `deleted_at` DATETIME(3) DEFAULT NULL,
    `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_media_public_id` (`public_id`),
    UNIQUE KEY `uk_media_user_external` (`user_id`, `platform`, `external_id`),
    KEY `idx_media_user_status` (`user_id`, `status`, `updated_at`),
    KEY `idx_media_user_deleted` (`user_id`, `deleted_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS `subtitle_track` (
    `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    `media_item_id` BIGINT UNSIGNED NOT NULL,
    `language` VARCHAR(20) NOT NULL,
    `source` VARCHAR(20) NOT NULL,
    `format` VARCHAR(20) NOT NULL,
    `is_original` TINYINT(1) NOT NULL DEFAULT 1,
    `status` VARCHAR(20) NOT NULL DEFAULT 'PENDING',
    `checksum` CHAR(64) DEFAULT NULL,
    `version` INT NOT NULL DEFAULT 1,
    `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_track_media_lang_version` (`media_item_id`, `language`, `is_original`, `version`),
    KEY `idx_track_media_status` (`media_item_id`, `status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS `subtitle_cue` (
    `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    `track_id` BIGINT UNSIGNED NOT NULL,
    `sequence_no` INT NOT NULL,
    `start_ms` BIGINT UNSIGNED NOT NULL,
    `end_ms` BIGINT UNSIGNED NOT NULL,
    `source_text` TEXT NOT NULL,
    `translation` TEXT DEFAULT NULL,
    `translation_lang` VARCHAR(20) DEFAULT NULL,
    `translation_provider` VARCHAR(64) DEFAULT NULL,
    `tokens` JSON DEFAULT NULL,
    `token_version` INT NOT NULL DEFAULT 1,
    `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_cue_track_sequence` (`track_id`, `sequence_no`),
    KEY `idx_cue_track_time` (`track_id`, `start_ms`, `end_ms`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS `async_job` (
    `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    `user_id` BIGINT UNSIGNED DEFAULT NULL,
    `job_type` VARCHAR(50) NOT NULL,
    `executor` VARCHAR(20) NOT NULL DEFAULT 'JAVA',
    `aggregate_type` VARCHAR(30) DEFAULT NULL,
    `aggregate_id` BIGINT UNSIGNED DEFAULT NULL,
    `status` VARCHAR(20) NOT NULL DEFAULT 'PENDING',
    `stage` VARCHAR(40) NOT NULL DEFAULT 'VALIDATING',
    `progress` TINYINT UNSIGNED NOT NULL DEFAULT 0,
    `priority` INT NOT NULL DEFAULT 0,
    `payload` JSON DEFAULT NULL,
    `attempt` INT NOT NULL DEFAULT 0,
    `max_attempt` INT NOT NULL DEFAULT 3,
    `next_run_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `locked_by` VARCHAR(100) DEFAULT NULL,
    `locked_at` DATETIME(3) DEFAULT NULL,
    `heartbeat_at` DATETIME(3) DEFAULT NULL,
    `last_error` TEXT DEFAULT NULL,
    `idempotency_key` VARCHAR(128) DEFAULT NULL,
    `result_ref` TEXT DEFAULT NULL,
    `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_job_idempotency` (`idempotency_key`),
    KEY `idx_job_claim` (`executor`, `status`, `next_run_at`, `priority`),
    KEY `idx_job_aggregate` (`aggregate_type`, `aggregate_id`, `created_at`),
    KEY `idx_job_user` (`user_id`, `created_at`),
    KEY `idx_job_heartbeat` (`status`, `heartbeat_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
