package com.lexiflow.infra.asyncjob.model;

public enum AsyncJobStage {
    VALIDATING,
    FETCHING_METADATA,
    UPLOADING,
    PROBING,
    TRANSCODING,
    ACQUIRING_SUBTITLE,
    DOWNLOADING_AUDIO,
    DOWNLOADING_MODEL,
    TRANSCRIBING,
    NORMALIZING,
    TRANSLATING,
    TOKENIZING,
    FINALIZING,
    READY
}
